import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/lib/auth-context";
import { ComponentsProvider } from "@/lib/components-context";
import { ChatProvider } from "@/lib/chat-context";
import { ChatWidget } from "@/components/chat/chat-widget";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <ComponentsProvider>
            <ChatProvider>
              {children}
              <ChatWidget />
              <Toaster />
            </ChatProvider>
          </ComponentsProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
